# Generated by Django 3.2.8 on 2021-10-30 12:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20211030_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.TextField(default=1, editable=False, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
