# Generated by Django 3.2.8 on 2021-11-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_auto_20211103_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
