# Generated by Django 3.2.8 on 2021-11-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_post_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
    ]
