# Generated by Django 3.2.8 on 2021-11-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_filters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filters',
            new_name='Filter',
        ),
    ]
