# Generated by Django 3.2.8 on 2021-11-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0011_auto_20211111_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterDetail',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='FilterProgram',
            new_name='Program',
        ),
        migrations.RenameModel(
            old_name='FilterSystem',
            new_name='System',
        ),
    ]
